version: "3.3"
services:
  mongo:
    container_name: linne-makeup-mongo
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - linne-makeup-mongo:/data/db
    ports:
      - 27018:27017
    restart: on-failure
    command: mongod
volumes:
  linne-makeup-mongo:
